unit UCL.FontIcons;

interface

const
  //  Control icons
  UF_MINIMIZE = #$E108;
  UF_MAXIMIZE = #$E003;
  UF_CLOSE = #$E10A;
  UF_BACK = #$E112;
  UF_CHECKBOX_FLAT_EMPTY = #$E003;
  UF_CHECKOUT_FLAT_CHECKED = #$E0A2;

  //  Common icons
  UF_SEARCH = #$E11A;
  UF_CHECK = #$E10B;
  UF_FULL_SCREEN = #$E1D9;
  UF_EXIT_FULL_SCREEN = #$E1D8;
  UF_DOWNLOAD = #$E118;
  UF_EDIT = #$E104;
  UF_THREE_LINE = #$E700;
  UF_HELP = #$E11B;
  UF_HOME = #$E10F;
  UF_LIKE = #$E19F;
  UF_LINK = #$E167;
  UF_LIST = #$E14C;
  UF_MESSAGE = #$E15F;
  UF_THREE_DOT = #$E10C;
  UF_MUTE = #$E198;
  UF_NEXT = #$E101;
  UF_OUTLINE_STAR = #$E1CE;
  UF_SOLID_STAR = #$E1CF;
  UF_SOLID_PAGE = #$E132;
  UF_OUTLINE_PAGE = #$E160;
  UF_PASTE = #$E16D;
  UF_PAUSE = #$E103;
  UF_PEOPLE = #$E125;
  UF_KEY = #$E192;
  UF_PHONE = #$E13A;
  UF_PIN = #$E141;
  UF_PLAY = #$E102;
  UF_PREVIOUS = #$E100;
  UF_UNDO = #$E10E;
  UF_REDO = #$E10D;
  UF_REFRESH = #$E149;
  UF_REPAIR = #$E15E;
  UF_REPEAT_ONE = #$E1CC;
  UF_WARNING = #$E1DE;
  UF_SAVE = #$E105;
  UF_SEND = #$E122;
  UF_SETTING = #$E115;
  UF_SHARE = #$E72D;
  UF_STOP = #$E15B;
  UF_SYNC = #$E117;
  UF_TAG = #$E1CB;

implementation

end.
